# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias kubectl="kubectl --server 10.253.0.1:8080"

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
